import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import Footer from "../components/Footer";
import {ThemeProvider} from "../context/ThemeContext";
import GlobalStyle from "../styles/global";

const workSans = Work_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <ThemeProvider>
          <html lang="en">
          <GlobalStyle />
          <body className={workSans.className}>
          <Header />
          {children}
          <Footer />
          </body>
          </html>
      </ThemeProvider>
  );
}

