// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  article: dynamic(() => import("./Article")),
  blog_image: dynamic(() => import("./BlogImage")),
  blog_posts_list: dynamic(() => import("./BlogPostsList")),
  blop_post_page_info: dynamic(() => import("./BlopPostPageInfo")),
  main_blog_post: dynamic(() => import("./MainBlogPost")),
  page_title: dynamic(() => import("./PageTitle")),
};
