// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  article: dynamic(() => import("./Article")),
  blog_posts: dynamic(() => import("./BlogPosts")),
  blog_posts_list: dynamic(() => import("./BlogPostsList")),
  main_blog_post: dynamic(() => import("./MainBlogPost")),
  page_title: dynamic(() => import("./PageTitle")),
};
